package vacancy.entities;

// Generated 12.04.2013 23:30:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Education generated by hbm2java
 */
@Entity
@Table(name = "education", schema = "public")
public class Education implements java.io.Serializable {

	private int ideducation;
	private String description;
	private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

	public Education() {
	}

	public Education(int ideducation) {
		this.ideducation = ideducation;
	}

	public Education(int ideducation, String description, Set<Vacancy> vacancies) {
		this.ideducation = ideducation;
		this.description = description;
		this.vacancies = vacancies;
	}

	@Id
	@Column(name = "ideducation", unique = true, nullable = false)
	public int getIdeducation() {
		return this.ideducation;
	}

	public void setIdeducation(int ideducation) {
		this.ideducation = ideducation;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "education")
	public Set<Vacancy> getVacancies() {
		return this.vacancies;
	}

	public void setVacancies(Set<Vacancy> vacancies) {
		this.vacancies = vacancies;
	}

}
