package vacancy.entities;

// Generated 12.04.2013 23:30:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name = "employer", schema = "public")
public class Employer implements java.io.Serializable {

	private int idemployer;
	private String name;
	private String telephone;
	private String contact;
	private String type;
	private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

	public Employer() {
	}

	public Employer(int idemployer) {
		this.idemployer = idemployer;
	}

	public Employer(int idemployer, String name, String telephone,
			String contact, String type, Set<Vacancy> vacancies) {
		this.idemployer = idemployer;
		this.name = name;
		this.telephone = telephone;
		this.contact = contact;
		this.type = type;
		this.vacancies = vacancies;
	}

	@Id
	@Column(name = "idemployer", unique = true, nullable = false)
	public int getIdemployer() {
		return this.idemployer;
	}

	public void setIdemployer(int idemployer) {
		this.idemployer = idemployer;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "telephone", length = 100)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "contact")
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employer")
	public Set<Vacancy> getVacancies() {
		return this.vacancies;
	}

	public void setVacancies(Set<Vacancy> vacancies) {
		this.vacancies = vacancies;
	}

}
