package vacancy.entities;

// Generated 12.04.2013 23:30:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shedule generated by hbm2java
 */
@Entity
@Table(name = "shedule", schema = "public")
public class Shedule implements java.io.Serializable {

	private int idshedule;
	private String description;
	private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

	public Shedule() {
	}

	public Shedule(int idshedule) {
		this.idshedule = idshedule;
	}

	public Shedule(int idshedule, String description, Set<Vacancy> vacancies) {
		this.idshedule = idshedule;
		this.description = description;
		this.vacancies = vacancies;
	}

	@Id
	@Column(name = "idshedule", unique = true, nullable = false)
	public int getIdshedule() {
		return this.idshedule;
	}

	public void setIdshedule(int idshedule) {
		this.idshedule = idshedule;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shedule")
	public Set<Vacancy> getVacancies() {
		return this.vacancies;
	}

	public void setVacancies(Set<Vacancy> vacancies) {
		this.vacancies = vacancies;
	}

}
