package vacancy.entities;

// Generated 12.04.2013 23:30:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sphere generated by hbm2java
 */
@Entity
@Table(name = "sphere", schema = "public")
public class Sphere implements java.io.Serializable {

	private int idsphere;
	private String name;
	private Set<Profession> professions = new HashSet<Profession>(0);

	public Sphere() {
	}

	public Sphere(int idsphere) {
		this.idsphere = idsphere;
	}

	public Sphere(int idsphere, String name, Set<Profession> professions) {
		this.idsphere = idsphere;
		this.name = name;
		this.professions = professions;
	}

	@Id
	@Column(name = "idsphere", unique = true, nullable = false)
	public int getIdsphere() {
		return this.idsphere;
	}

	public void setIdsphere(int idsphere) {
		this.idsphere = idsphere;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sphere")
	public Set<Profession> getProfessions() {
		return this.professions;
	}

	public void setProfessions(Set<Profession> professions) {
		this.professions = professions;
	}

}
