package vacancy.entities;

// Generated 12.04.2013 23:30:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacancy generated by hbm2java
 */
@Entity
@Table(name = "vacancy", schema = "public")
public class Vacancy implements java.io.Serializable {

	private int id;
	private City city;
	private Employer employer;
	private Employment employment;
	private Shedule shedule;
	private Education education;
	private String post;
	private String experience;
	private String desires;
	private Date dat;
	private Set<Profession> professions = new HashSet<Profession>(0);

	public Vacancy() {
	}

	public Vacancy(int id) {
		this.id = id;
	}

	public Vacancy(int id, City city, Employer employer, Employment employment,
			Shedule shedule, Education education, String post,
			String experience, String desires, Date dat,
			Set<Profession> professions) {
		this.id = id;
		this.city = city;
		this.employer = employer;
		this.employment = employment;
		this.shedule = shedule;
		this.education = education;
		this.post = post;
		this.experience = experience;
		this.desires = desires;
		this.dat = dat;
		this.professions = professions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcity")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idemployer")
	public Employer getEmployer() {
		return this.employer;
	}

	public void setEmployer(Employer employer) {
		this.employer = employer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idemployment")
	public Employment getEmployment() {
		return this.employment;
	}

	public void setEmployment(Employment employment) {
		this.employment = employment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idshedule")
	public Shedule getShedule() {
		return this.shedule;
	}

	public void setShedule(Shedule shedule) {
		this.shedule = shedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ideducation")
	public Education getEducation() {
		return this.education;
	}

	public void setEducation(Education education) {
		this.education = education;
	}

	@Column(name = "post")
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "experience", length = 100)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "desires")
	public String getDesires() {
		return this.desires;
	}

	public void setDesires(String desires) {
		this.desires = desires;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dat", length = 13)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vac_prof", schema = "public", joinColumns = { @JoinColumn(name = "idvacancy", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idprofession", nullable = false, updatable = false) })
	public Set<Profession> getProfessions() {
		return this.professions;
	}

	public void setProfessions(Set<Profession> professions) {
		this.professions = professions;
	}

}
